name: aegis_open_network
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_card_swiper: ^7.0.2
  flutter_markdown_plus: ^1.0.5
  flutter_ai_toolkit: ^0.10.0
  dynamic_color: ^1.8.1
  go_router: ^16.2.1
  shared_preferences: ^2.5.3
  split_view: ^3.2.1
  dartx: ^1.2.0
  uuid: ^4.5.1
  path_provider: ^2.1.5
  tostore: ^2.2.2
  geolocator: ^14.0.2

  ### lib/services/meshtastic.dart
  protobuf: ^5.0.0
  flutter_blue_plus: ^2.0.0
  permission_handler: ^12.0.1
  logging: ^1.3.0
  fixnum: ^1.1.1

  ###
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  icons_launcher: ^3.0.3
  openai_dart: ^0.5.5
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/avatars/
    - assets/avatars/ai/